/*
* generated by Xtext
*/
package org.xtext.example.mydsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {
	
	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser createParser() {
		org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser result = new org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getDomainmodelAccess().getElementAlternatives_0(), "rule__Domainmodel__ElementAlternatives_0");
					put(grammarAccess.getTypeDefinitionAccess().getAlternatives(), "rule__TypeDefinition__Alternatives");
					put(grammarAccess.getChannelDefintionAccess().getTypeAlternatives_3_0(), "rule__ChannelDefintion__TypeAlternatives_3_0");
					put(grammarAccess.getObjectAccess().getAlternatives(), "rule__Object__Alternatives");
					put(grammarAccess.getRoleAccess().getRoleTypeAlternatives_0_0(), "rule__Role__RoleTypeAlternatives_0_0");
					put(grammarAccess.getProcessStartElementsAccess().getAlternatives(), "rule__ProcessStartElements__Alternatives");
					put(grammarAccess.getProcessElementsAccess().getAlternatives(), "rule__ProcessElements__Alternatives");
					put(grammarAccess.getProcessChartElementsAccess().getAlternatives(), "rule__ProcessChartElements__Alternatives");
					put(grammarAccess.getLoopAccess().getAlternatives_2(), "rule__Loop__Alternatives_2");
					put(grammarAccess.getIFQueryAccess().getAlternatives_3_0(), "rule__IFQuery__Alternatives_3_0");
					put(grammarAccess.getQueryTypesAccess().getAlternatives(), "rule__QueryTypes__Alternatives");
					put(grammarAccess.getQueryAccess().getAlternatives(), "rule__Query__Alternatives");
					put(grammarAccess.getBooleanQueryAccess().getBooleanAlternatives_2_1_0(), "rule__BooleanQuery__BooleanAlternatives_2_1_0");
					put(grammarAccess.getDataQueryAccess().getConditionAlternatives_2_0(), "rule__DataQuery__ConditionAlternatives_2_0");
					put(grammarAccess.getBraceQueryAccess().getAlternatives_3_0(), "rule__BraceQuery__Alternatives_3_0");
					put(grammarAccess.getPlayerQueryAccess().getBooleanAlternatives_4_1_0(), "rule__PlayerQuery__BooleanAlternatives_4_1_0");
					put(grammarAccess.getCommunicationAccess().getImportanceAlternatives_0_0(), "rule__Communication__ImportanceAlternatives_0_0");
					put(grammarAccess.getCommunicationAccess().getExecutionAlternatives_2_0(), "rule__Communication__ExecutionAlternatives_2_0");
					put(grammarAccess.getActivityAccess().getImportanceAlternatives_0_0(), "rule__Activity__ImportanceAlternatives_0_0");
					put(grammarAccess.getActivityAccess().getExecutionAlternatives_2_0(), "rule__Activity__ExecutionAlternatives_2_0");
					put(grammarAccess.getSystemworkAccess().getImportanceAlternatives_1_0(), "rule__Systemwork__ImportanceAlternatives_1_0");
					put(grammarAccess.getSystemworkAccess().getExecutionAlternatives_3_0(), "rule__Systemwork__ExecutionAlternatives_3_0");
					put(grammarAccess.getDatatypeAccess().getGroup(), "rule__Datatype__Group__0");
					put(grammarAccess.getSystemtypeAccess().getGroup(), "rule__Systemtype__Group__0");
					put(grammarAccess.getChannelDefintionAccess().getGroup(), "rule__ChannelDefintion__Group__0");
					put(grammarAccess.getRoletypeAccess().getGroup(), "rule__Roletype__Group__0");
					put(grammarAccess.getStateAccess().getGroup(), "rule__State__Group__0");
					put(grammarAccess.getTaskAccess().getGroup(), "rule__Task__Group__0");
					put(grammarAccess.getTaskAccess().getGroup_3(), "rule__Task__Group_3__0");
					put(grammarAccess.getTaskAccess().getGroup_3_1(), "rule__Task__Group_3_1__0");
					put(grammarAccess.getMessageAccess().getGroup(), "rule__Message__Group__0");
					put(grammarAccess.getMessageAccess().getGroup_3(), "rule__Message__Group_3__0");
					put(grammarAccess.getMessageAccess().getGroup_3_1(), "rule__Message__Group_3_1__0");
					put(grammarAccess.getFunctionAccess().getGroup(), "rule__Function__Group__0");
					put(grammarAccess.getFunctionAccess().getGroup_3(), "rule__Function__Group_3__0");
					put(grammarAccess.getFunctionAccess().getGroup_3_1(), "rule__Function__Group_3_1__0");
					put(grammarAccess.getFunctionAccess().getGroup_5(), "rule__Function__Group_5__0");
					put(grammarAccess.getInterviewAccess().getGroup(), "rule__Interview__Group__0");
					put(grammarAccess.getBooleanAccess().getGroup(), "rule__Boolean__Group__0");
					put(grammarAccess.getSystemAccess().getGroup(), "rule__System__Group__0");
					put(grammarAccess.getDataAccess().getGroup(), "rule__Data__Group__0");
					put(grammarAccess.getRoleAccess().getGroup(), "rule__Role__Group__0");
					put(grammarAccess.getBusinessProcessAccess().getGroup(), "rule__BusinessProcess__Group__0");
					put(grammarAccess.getChartAccess().getGroup(), "rule__Chart__Group__0");
					put(grammarAccess.getStartTimeAlternativeAccess().getGroup(), "rule__StartTimeAlternative__Group__0");
					put(grammarAccess.getStartTimeAlternativeAccess().getGroup_9(), "rule__StartTimeAlternative__Group_9__0");
					put(grammarAccess.getTimeAlternativeAccess().getGroup(), "rule__TimeAlternative__Group__0");
					put(grammarAccess.getTimeAlternativeAccess().getGroup_9(), "rule__TimeAlternative__Group_9__0");
					put(grammarAccess.getStartAlternativeAccess().getGroup(), "rule__StartAlternative__Group__0");
					put(grammarAccess.getStartAlternativeAccess().getGroup_9(), "rule__StartAlternative__Group_9__0");
					put(grammarAccess.getAlternativeAccess().getGroup(), "rule__Alternative__Group__0");
					put(grammarAccess.getAlternativeAccess().getGroup_9(), "rule__Alternative__Group_9__0");
					put(grammarAccess.getLoopAccess().getGroup(), "rule__Loop__Group__0");
					put(grammarAccess.getIFQueryAccess().getGroup(), "rule__IFQuery__Group__0");
					put(grammarAccess.getIFQueryAccess().getGroup_3(), "rule__IFQuery__Group_3__0");
					put(grammarAccess.getIFQueryAccess().getGroup_8(), "rule__IFQuery__Group_8__0");
					put(grammarAccess.getBooleanQueryAccess().getGroup(), "rule__BooleanQuery__Group__0");
					put(grammarAccess.getBooleanQueryAccess().getGroup_2(), "rule__BooleanQuery__Group_2__0");
					put(grammarAccess.getDataQueryAccess().getGroup(), "rule__DataQuery__Group__0");
					put(grammarAccess.getBraceQueryAccess().getGroup(), "rule__BraceQuery__Group__0");
					put(grammarAccess.getBraceQueryAccess().getGroup_3(), "rule__BraceQuery__Group_3__0");
					put(grammarAccess.getPlayerQueryAccess().getGroup(), "rule__PlayerQuery__Group__0");
					put(grammarAccess.getPlayerQueryAccess().getGroup_4(), "rule__PlayerQuery__Group_4__0");
					put(grammarAccess.getCommunicationAccess().getGroup(), "rule__Communication__Group__0");
					put(grammarAccess.getCommunicationAccess().getGroup_9(), "rule__Communication__Group_9__0");
					put(grammarAccess.getCommunicationAccess().getGroup_9_1(), "rule__Communication__Group_9_1__0");
					put(grammarAccess.getCommunicationAccess().getGroup_11(), "rule__Communication__Group_11__0");
					put(grammarAccess.getActivityAccess().getGroup(), "rule__Activity__Group__0");
					put(grammarAccess.getActivityAccess().getGroup_6(), "rule__Activity__Group_6__0");
					put(grammarAccess.getActivityAccess().getGroup_6_1(), "rule__Activity__Group_6_1__0");
					put(grammarAccess.getSystemworkAccess().getGroup(), "rule__Systemwork__Group__0");
					put(grammarAccess.getSystemworkAccess().getGroup_0(), "rule__Systemwork__Group_0__0");
					put(grammarAccess.getSystemworkAccess().getGroup_9(), "rule__Systemwork__Group_9__0");
					put(grammarAccess.getSystemworkAccess().getGroup_9_1(), "rule__Systemwork__Group_9_1__0");
					put(grammarAccess.getDomainmodelAccess().getElementAssignment(), "rule__Domainmodel__ElementAssignment");
					put(grammarAccess.getDatatypeAccess().getPackageAssignment_1(), "rule__Datatype__PackageAssignment_1");
					put(grammarAccess.getDatatypeAccess().getNameAssignment_4(), "rule__Datatype__NameAssignment_4");
					put(grammarAccess.getSystemtypeAccess().getPackageAssignment_1(), "rule__Systemtype__PackageAssignment_1");
					put(grammarAccess.getSystemtypeAccess().getNameAssignment_4(), "rule__Systemtype__NameAssignment_4");
					put(grammarAccess.getSystemtypeAccess().getFunctionsAssignment_6(), "rule__Systemtype__FunctionsAssignment_6");
					put(grammarAccess.getChannelDefintionAccess().getPackageAssignment_1(), "rule__ChannelDefintion__PackageAssignment_1");
					put(grammarAccess.getChannelDefintionAccess().getTypeAssignment_3(), "rule__ChannelDefintion__TypeAssignment_3");
					put(grammarAccess.getChannelDefintionAccess().getNameAssignment_5(), "rule__ChannelDefintion__NameAssignment_5");
					put(grammarAccess.getRoletypeAccess().getPackageAssignment_1(), "rule__Roletype__PackageAssignment_1");
					put(grammarAccess.getRoletypeAccess().getNameAssignment_4(), "rule__Roletype__NameAssignment_4");
					put(grammarAccess.getRoletypeAccess().getStateAssignment_6(), "rule__Roletype__StateAssignment_6");
					put(grammarAccess.getRoletypeAccess().getTasksAssignment_7(), "rule__Roletype__TasksAssignment_7");
					put(grammarAccess.getRoletypeAccess().getMessagesAssignment_8(), "rule__Roletype__MessagesAssignment_8");
					put(grammarAccess.getStateAccess().getNameAssignment_1(), "rule__State__NameAssignment_1");
					put(grammarAccess.getTaskAccess().getNameAssignment_1(), "rule__Task__NameAssignment_1");
					put(grammarAccess.getTaskAccess().getParameterAssignment_3_0(), "rule__Task__ParameterAssignment_3_0");
					put(grammarAccess.getTaskAccess().getParameterAssignment_3_1_1(), "rule__Task__ParameterAssignment_3_1_1");
					put(grammarAccess.getMessageAccess().getNameAssignment_1(), "rule__Message__NameAssignment_1");
					put(grammarAccess.getMessageAccess().getParameterAssignment_3_0(), "rule__Message__ParameterAssignment_3_0");
					put(grammarAccess.getMessageAccess().getParameterAssignment_3_1_1(), "rule__Message__ParameterAssignment_3_1_1");
					put(grammarAccess.getFunctionAccess().getNameAssignment_1(), "rule__Function__NameAssignment_1");
					put(grammarAccess.getFunctionAccess().getParameterAssignment_3_0(), "rule__Function__ParameterAssignment_3_0");
					put(grammarAccess.getFunctionAccess().getParameterAssignment_3_1_1(), "rule__Function__ParameterAssignment_3_1_1");
					put(grammarAccess.getFunctionAccess().getReturnValueAssignment_5_0(), "rule__Function__ReturnValueAssignment_5_0");
					put(grammarAccess.getFunctionAccess().getReturnArgumentAssignment_5_1(), "rule__Function__ReturnArgumentAssignment_5_1");
					put(grammarAccess.getFunctionAccess().getReturnBoolAssignment_5_2(), "rule__Function__ReturnBoolAssignment_5_2");
					put(grammarAccess.getInterviewAccess().getPackageAssignment_1(), "rule__Interview__PackageAssignment_1");
					put(grammarAccess.getInterviewAccess().getNameAssignment_4(), "rule__Interview__NameAssignment_4");
					put(grammarAccess.getInterviewAccess().getMainPlayerAssignment_7(), "rule__Interview__MainPlayerAssignment_7");
					put(grammarAccess.getInterviewAccess().getObjectsAssignment_8(), "rule__Interview__ObjectsAssignment_8");
					put(grammarAccess.getInterviewAccess().getProcessAssignment_9(), "rule__Interview__ProcessAssignment_9");
					put(grammarAccess.getBooleanAccess().getTypeAssignment_1(), "rule__Boolean__TypeAssignment_1");
					put(grammarAccess.getBooleanAccess().getNameAssignment_2(), "rule__Boolean__NameAssignment_2");
					put(grammarAccess.getSystemAccess().getTypeAssignment_1(), "rule__System__TypeAssignment_1");
					put(grammarAccess.getSystemAccess().getNameAssignment_2(), "rule__System__NameAssignment_2");
					put(grammarAccess.getDataAccess().getTypeAssignment_1(), "rule__Data__TypeAssignment_1");
					put(grammarAccess.getDataAccess().getNameAssignment_2(), "rule__Data__NameAssignment_2");
					put(grammarAccess.getRoleAccess().getRoleTypeAssignment_0(), "rule__Role__RoleTypeAssignment_0");
					put(grammarAccess.getRoleAccess().getTypeAssignment_1(), "rule__Role__TypeAssignment_1");
					put(grammarAccess.getRoleAccess().getNameAssignment_2(), "rule__Role__NameAssignment_2");
					put(grammarAccess.getBusinessProcessAccess().getNameAssignment_1(), "rule__BusinessProcess__NameAssignment_1");
					put(grammarAccess.getBusinessProcessAccess().getElementAssignment_3(), "rule__BusinessProcess__ElementAssignment_3");
					put(grammarAccess.getChartAccess().getStartElementsAssignment_3(), "rule__Chart__StartElementsAssignment_3");
					put(grammarAccess.getChartAccess().getFollowedElementsAssignment_7(), "rule__Chart__FollowedElementsAssignment_7");
					put(grammarAccess.getStartTimeAlternativeAccess().getMostlyAlternativeAssignment_3(), "rule__StartTimeAlternative__MostlyAlternativeAssignment_3");
					put(grammarAccess.getStartTimeAlternativeAccess().getSometimesAlternativeAssignment_7(), "rule__StartTimeAlternative__SometimesAlternativeAssignment_7");
					put(grammarAccess.getStartTimeAlternativeAccess().getSometimesAlternativeAssignment_9_2(), "rule__StartTimeAlternative__SometimesAlternativeAssignment_9_2");
					put(grammarAccess.getTimeAlternativeAccess().getMostlyAlternativeAssignment_3(), "rule__TimeAlternative__MostlyAlternativeAssignment_3");
					put(grammarAccess.getTimeAlternativeAccess().getSometimeAlternativeAssignment_7(), "rule__TimeAlternative__SometimeAlternativeAssignment_7");
					put(grammarAccess.getTimeAlternativeAccess().getSometimeAlternativeAssignment_9_2(), "rule__TimeAlternative__SometimeAlternativeAssignment_9_2");
					put(grammarAccess.getStartAlternativeAccess().getAlternativeAssignment_3(), "rule__StartAlternative__AlternativeAssignment_3");
					put(grammarAccess.getStartAlternativeAccess().getAlternativeAssignment_7(), "rule__StartAlternative__AlternativeAssignment_7");
					put(grammarAccess.getStartAlternativeAccess().getAlternativeAssignment_9_2(), "rule__StartAlternative__AlternativeAssignment_9_2");
					put(grammarAccess.getAlternativeAccess().getAlternativeAssignment_3(), "rule__Alternative__AlternativeAssignment_3");
					put(grammarAccess.getAlternativeAccess().getAlternativeAssignment_7(), "rule__Alternative__AlternativeAssignment_7");
					put(grammarAccess.getAlternativeAccess().getAlternativeAssignment_9_2(), "rule__Alternative__AlternativeAssignment_9_2");
					put(grammarAccess.getLoopAccess().getUncounterAssignment_2_0(), "rule__Loop__UncounterAssignment_2_0");
					put(grammarAccess.getLoopAccess().getCounterAssignment_2_1(), "rule__Loop__CounterAssignment_2_1");
					put(grammarAccess.getLoopAccess().getElementsAssignment_5(), "rule__Loop__ElementsAssignment_5");
					put(grammarAccess.getIFQueryAccess().getQueriesAssignment_2(), "rule__IFQuery__QueriesAssignment_2");
					put(grammarAccess.getIFQueryAccess().getQueriesAssignment_3_1(), "rule__IFQuery__QueriesAssignment_3_1");
					put(grammarAccess.getIFQueryAccess().getElementsAssignment_6(), "rule__IFQuery__ElementsAssignment_6");
					put(grammarAccess.getIFQueryAccess().getElementsAssignment_8_2(), "rule__IFQuery__ElementsAssignment_8_2");
					put(grammarAccess.getBooleanQueryAccess().getBooleanValueAssignment_1(), "rule__BooleanQuery__BooleanValueAssignment_1");
					put(grammarAccess.getBooleanQueryAccess().getBooleanAssignment_2_1(), "rule__BooleanQuery__BooleanAssignment_2_1");
					put(grammarAccess.getDataQueryAccess().getExclamationAssignment_0(), "rule__DataQuery__ExclamationAssignment_0");
					put(grammarAccess.getDataQueryAccess().getObjectOneAssignment_1(), "rule__DataQuery__ObjectOneAssignment_1");
					put(grammarAccess.getDataQueryAccess().getConditionAssignment_2(), "rule__DataQuery__ConditionAssignment_2");
					put(grammarAccess.getDataQueryAccess().getObjectTwoAssignment_3(), "rule__DataQuery__ObjectTwoAssignment_3");
					put(grammarAccess.getBraceQueryAccess().getQueriesAssignment_2(), "rule__BraceQuery__QueriesAssignment_2");
					put(grammarAccess.getBraceQueryAccess().getQueriesAssignment_3_1(), "rule__BraceQuery__QueriesAssignment_3_1");
					put(grammarAccess.getPlayerQueryAccess().getPlayerAssignment_1(), "rule__PlayerQuery__PlayerAssignment_1");
					put(grammarAccess.getPlayerQueryAccess().getStatusAssignment_3(), "rule__PlayerQuery__StatusAssignment_3");
					put(grammarAccess.getPlayerQueryAccess().getBooleanAssignment_4_1(), "rule__PlayerQuery__BooleanAssignment_4_1");
					put(grammarAccess.getCommunicationAccess().getImportanceAssignment_0(), "rule__Communication__ImportanceAssignment_0");
					put(grammarAccess.getCommunicationAccess().getSenderAssignment_1(), "rule__Communication__SenderAssignment_1");
					put(grammarAccess.getCommunicationAccess().getExecutionAssignment_2(), "rule__Communication__ExecutionAssignment_2");
					put(grammarAccess.getCommunicationAccess().getReceiverAssignment_5(), "rule__Communication__ReceiverAssignment_5");
					put(grammarAccess.getCommunicationAccess().getMessageAssignment_7(), "rule__Communication__MessageAssignment_7");
					put(grammarAccess.getCommunicationAccess().getParameterAssignment_9_0(), "rule__Communication__ParameterAssignment_9_0");
					put(grammarAccess.getCommunicationAccess().getParameterAssignment_9_1_1(), "rule__Communication__ParameterAssignment_9_1_1");
					put(grammarAccess.getCommunicationAccess().getChannelAssignment_11_1(), "rule__Communication__ChannelAssignment_11_1");
					put(grammarAccess.getActivityAccess().getImportanceAssignment_0(), "rule__Activity__ImportanceAssignment_0");
					put(grammarAccess.getActivityAccess().getPlayerAssignment_1(), "rule__Activity__PlayerAssignment_1");
					put(grammarAccess.getActivityAccess().getExecutionAssignment_2(), "rule__Activity__ExecutionAssignment_2");
					put(grammarAccess.getActivityAccess().getTaskAssignment_4(), "rule__Activity__TaskAssignment_4");
					put(grammarAccess.getActivityAccess().getParameterAssignment_6_0(), "rule__Activity__ParameterAssignment_6_0");
					put(grammarAccess.getActivityAccess().getParameterAssignment_6_1_1(), "rule__Activity__ParameterAssignment_6_1_1");
					put(grammarAccess.getSystemworkAccess().getReturnObjectAssignment_0_0(), "rule__Systemwork__ReturnObjectAssignment_0_0");
					put(grammarAccess.getSystemworkAccess().getImportanceAssignment_1(), "rule__Systemwork__ImportanceAssignment_1");
					put(grammarAccess.getSystemworkAccess().getPlayerAssignment_2(), "rule__Systemwork__PlayerAssignment_2");
					put(grammarAccess.getSystemworkAccess().getExecutionAssignment_3(), "rule__Systemwork__ExecutionAssignment_3");
					put(grammarAccess.getSystemworkAccess().getSystemAssignment_5(), "rule__Systemwork__SystemAssignment_5");
					put(grammarAccess.getSystemworkAccess().getFunctionAssignment_7(), "rule__Systemwork__FunctionAssignment_7");
					put(grammarAccess.getSystemworkAccess().getParameterAssignment_9_0(), "rule__Systemwork__ParameterAssignment_9_0");
					put(grammarAccess.getSystemworkAccess().getParameterAssignment_9_1_1(), "rule__Systemwork__ParameterAssignment_9_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser typedParser = (org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser) parser;
			typedParser.entryRuleDomainmodel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
